-- =====================================================
-- GESTIÓN PLANEAMIENTO DATABASE - DDL
-- Clean and Human-Readable Version
-- =====================================================

-- Create Database
CREATE DATABASE gestion_planeamiento
    WITH ENCODING = 'UTF8'
    LOCALE = 'en_US.utf8';

-- =====================================================
-- CORE TABLES
-- =====================================================

-- Roles Table
CREATE TABLE tb_roles (
                          id_rol BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          nombre_rol VARCHAR(255) NOT NULL UNIQUE
);

-- Permissions Table
CREATE TABLE tb_permisos (
                             id_permiso BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             nombre_permiso VARCHAR(255) NOT NULL UNIQUE,
                             descripcion_permiso VARCHAR(255)
);

-- Role-Permissions Relationship Table
CREATE TABLE tb_rol_permisos (
                                 id_rol_fk BIGINT NOT NULL,
                                 id_permiso_fk BIGINT NOT NULL,
                                 PRIMARY KEY (id_rol_fk, id_permiso_fk)
);

-- Users Table
CREATE TABLE tb_usuarios (
                             id_user BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             id_rol_fk BIGINT NOT NULL,
                             nombre VARCHAR(255),
                             apellido VARCHAR(255),
                             username VARCHAR(255),
                             password VARCHAR(255),
                             correo VARCHAR(255),
                             cedula VARCHAR(255)
);

-- =====================================================
-- ACADEMIC STRUCTURE TABLES
-- =====================================================

-- Grades Table
CREATE TABLE tb_grado (
                          id_grado BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          nombre_grado VARCHAR(255)
);

-- Sections Table
CREATE TABLE tb_seccion (
                            id_seccion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            nombre_seccion VARCHAR(255)
);

-- Grade-Section Relationship Table
CREATE TABLE tb_grado_seccion (
                                  id_grado_seccion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  id_grado_fk BIGINT,
                                  id_seccion_fk BIGINT
);

-- Subjects Table
CREATE TABLE tb_materia (
                            id_materia BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            nombre_materia VARCHAR(255)
);

-- =====================================================
-- SCHEDULE TABLE
-- =====================================================

-- Schedule Table
CREATE TABLE tb_horario (
                            id_horario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            grado_seccion_id BIGINT UNIQUE,
                            id_materia BIGINT UNIQUE,
                            user_id BIGINT,
                            dia VARCHAR(255) CHECK (dia IN ('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES')),
                            turno VARCHAR(255) CHECK (turno IN ('MANIANA', 'TARDE')),
                            horario_inicio TIME(6),
                            horario_fin TIME(6)
);

-- =====================================================
-- PLANNING TABLES
-- =====================================================

-- Planning Details Table
CREATE TABLE tb_planeamiento_detalle (
                                         id_planeamiento_detalle BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         unidad_tematica VARCHAR(255),
                                         fecha_desarrollo DATE,
                                         recursos VARCHAR(255),
                                         observacion VARCHAR(255)
);

-- Main Planning Table
CREATE TABLE tb_planeamiento (
                                 id_planeamiento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 grado_seccion_id BIGINT UNIQUE,
                                 materia_id BIGINT UNIQUE,
                                 plan_detalle_id BIGINT UNIQUE,
                                 id_user BIGINT,
                                 raw_file VARCHAR(255)
);

-- Planning Capacities Table
CREATE TABLE tb_planeamiento_capacidades (
                                             id_plan_cap BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             id_planeamiento_fk BIGINT NOT NULL,
                                             capacidad VARCHAR(255) NOT NULL
);

-- Planning Indicators Table
CREATE TABLE tb_planeamiento_indicadores (
                                             id_plan_indicadores BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             id_planeamiento_fk BIGINT NOT NULL,
                                             indicador VARCHAR(255) NOT NULL
);

-- Planning Activities Table
CREATE TABLE tb_planeamiento_actividades (
                                             id_plan_act BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             id_planeamiento_fk BIGINT,
                                             actividad VARCHAR(255),
                                             actividad_pertenece_tipo VARCHAR(255) CHECK (actividad_pertenece_tipo IN ('ALUMNO', 'DOCENTE', 'NINGUNO')),
                                             actividad_realiza_tipo VARCHAR(255) CHECK (actividad_realiza_tipo IN ('CIERRE', 'APERTURA', 'DESARROLLO', 'SIMPLE')),
                                             desarrollo_directo VARCHAR(255)
);

-- Planning Comments Table
CREATE TABLE tb_planeamiento_comentario (
                                            id_planeamiento_comentario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            id_planeamiento_fk BIGINT NOT NULL,
                                            id_user BIGINT NOT NULL,
                                            comentario VARCHAR(255) NOT NULL,
                                            root_comment_id INTEGER
);

-- =====================================================
-- AUDIT TABLE
-- =====================================================

-- Audit Table
CREATE TABLE tb_auditoria (
                              auditoria_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              user_id INTEGER,
                              operacion TEXT,
                              nombre_tabla TEXT,
                              fila_tabla BIGINT,
                              nuevos_datos JSON,
                              viejos_datos JSON,
                              timestamp TIMESTAMP,
                              ip_address TEXT,
                              user_agent TEXT
);

-- =====================================================
-- FOREIGN KEY CONSTRAINTS
-- =====================================================

-- Role-Permission Relationships
ALTER TABLE tb_rol_permisos
    ADD CONSTRAINT fk_rol_permisos_rol
        FOREIGN KEY (id_rol_fk) REFERENCES tb_roles(id_rol);

ALTER TABLE tb_rol_permisos
    ADD CONSTRAINT fk_rol_permisos_permiso
        FOREIGN KEY (id_permiso_fk) REFERENCES tb_permisos(id_permiso);

-- User Relationships
ALTER TABLE tb_usuarios
    ADD CONSTRAINT fk_usuarios_rol
        FOREIGN KEY (id_rol_fk) REFERENCES tb_roles(id_rol);

-- Grade-Section Relationships
ALTER TABLE tb_grado_seccion
    ADD CONSTRAINT fk_grado_seccion_grado
        FOREIGN KEY (id_grado_fk) REFERENCES tb_grado(id_grado);

ALTER TABLE tb_grado_seccion
    ADD CONSTRAINT fk_grado_seccion_seccion
        FOREIGN KEY (id_seccion_fk) REFERENCES tb_seccion(id_seccion);

-- Schedule Relationships
ALTER TABLE tb_horario
    ADD CONSTRAINT fk_horario_grado_seccion
        FOREIGN KEY (grado_seccion_id) REFERENCES tb_grado_seccion(id_grado_seccion);

ALTER TABLE tb_horario
    ADD CONSTRAINT fk_horario_materia
        FOREIGN KEY (id_materia) REFERENCES tb_materia(id_materia);

ALTER TABLE tb_horario
    ADD CONSTRAINT fk_horario_usuario
        FOREIGN KEY (user_id) REFERENCES tb_usuarios(id_user);

-- Planning Relationships
ALTER TABLE tb_planeamiento
    ADD CONSTRAINT fk_planeamiento_grado_seccion
        FOREIGN KEY (grado_seccion_id) REFERENCES tb_grado_seccion(id_grado_seccion);

ALTER TABLE tb_planeamiento
    ADD CONSTRAINT fk_planeamiento_materia
        FOREIGN KEY (materia_id) REFERENCES tb_materia(id_materia);

ALTER TABLE tb_planeamiento
    ADD CONSTRAINT fk_planeamiento_detalle
        FOREIGN KEY (plan_detalle_id) REFERENCES tb_planeamiento_detalle(id_planeamiento_detalle);

ALTER TABLE tb_planeamiento
    ADD CONSTRAINT fk_planeamiento_usuario
        FOREIGN KEY (id_user) REFERENCES tb_usuarios(id_user);

-- Planning Capacities Relationships
ALTER TABLE tb_planeamiento_capacidades
    ADD CONSTRAINT fk_capacidades_planeamiento
        FOREIGN KEY (id_planeamiento_fk) REFERENCES tb_planeamiento(id_planeamiento);

-- Planning Indicators Relationships
ALTER TABLE tb_planeamiento_indicadores
    ADD CONSTRAINT fk_indicadores_planeamiento
        FOREIGN KEY (id_planeamiento_fk) REFERENCES tb_planeamiento(id_planeamiento);

-- Planning Activities Relationships
ALTER TABLE tb_planeamiento_actividades
    ADD CONSTRAINT fk_actividades_planeamiento
        FOREIGN KEY (id_planeamiento_fk) REFERENCES tb_planeamiento(id_planeamiento);

-- Planning Comments Relationships
ALTER TABLE tb_planeamiento_comentario
    ADD CONSTRAINT fk_comentario_planeamiento
        FOREIGN KEY (id_planeamiento_fk) REFERENCES tb_planeamiento(id_planeamiento);

ALTER TABLE tb_planeamiento_comentario
    ADD CONSTRAINT fk_comentario_usuario
        FOREIGN KEY (id_user) REFERENCES tb_usuarios(id_user);

-- Audit Relationships
ALTER TABLE tb_auditoria
    ADD CONSTRAINT fk_auditoria_usuario
        FOREIGN KEY (user_id) REFERENCES tb_usuarios(id_user);