-- =====================================================
-- GESTIÓN PLANEAMIENTO DATABASE - DDL

-- CORE TABLES
-- =====================================================

-- Roles Table
CREATE TABLE tb_roles (
                          id_rol BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          nombre_rol VARCHAR(255) NOT NULL UNIQUE
);

-- Permissions Table
CREATE TABLE tb_permisos (
                             id_permiso BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             nombre_permiso VARCHAR(255) NOT NULL UNIQUE,
                             descripcion_permiso VARCHAR(255)
);

-- Role-Permissions Relationship Table
CREATE TABLE tb_rol_permisos (
                                 id_rol_fk BIGINT NOT NULL REFERENCES tb_roles(id_rol),
                                 id_permiso_fk BIGINT NOT NULL REFERENCES tb_permisos(id_permiso),
                                 PRIMARY KEY (id_rol_fk, id_permiso_fk)
);

-- Users Table
CREATE TABLE tb_usuarios (
                             id_user BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             id_rol_fk BIGINT NOT NULL REFERENCES tb_roles(id_rol),
                             nombre VARCHAR(255),
                             apellido VARCHAR(255),
                             username VARCHAR(255),
                             password VARCHAR(255),
                             correo VARCHAR(255),
                             cedula VARCHAR(255)
);

-- =====================================================
-- ACADEMIC STRUCTURE TABLES
-- =====================================================

-- Grades Table
CREATE TABLE tb_grado (
                          id_grado BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          nombre_grado VARCHAR(255)
);

-- Sections Table
CREATE TABLE tb_seccion (
                            id_seccion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            id_grado_fk BIGINT REFERENCES tb_grado(id_grado),
                            nombre_seccion VARCHAR(255)
);

-- Subjects Table
CREATE TABLE tb_materia (
                            id_materia BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            nombre_materia VARCHAR(255)
);

-- =====================================================
-- SCHEDULE TABLE
-- =====================================================

-- Schedule Table
CREATE TABLE tb_horario (
                            id_horario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            grado_id_fk BIGINT REFERENCES  tb_grado(id_grado),
                            id_materia BIGINT UNIQUE REFERENCES tb_materia(id_materia),
                            user_id BIGINT REFERENCES tb_usuarios(id_user),
                            dia VARCHAR(255) CHECK (dia IN ('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES')),
                            turno VARCHAR(255) CHECK (turno IN ('MANIANA', 'TARDE')),
                            horario_inicio TIME(6),
                            horario_fin TIME(6)
);

-- =====================================================
-- PLANNING TABLES
-- =====================================================

-- Planning Details Table
CREATE TABLE tb_planeamiento_detalle (
                                         id_planeamiento_detalle BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         unidad_tematica VARCHAR(255),
                                         fecha_desarrollo DATE,
                                         recursos VARCHAR(255),
                                         observacion VARCHAR(255)
);

-- Main Planning Table
CREATE TABLE tb_planeamiento (
                                 id_planeamiento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 id_grado BIGINT UNIQUE REFERENCES tb_grado(id_grado),
                                 materia_id BIGINT UNIQUE REFERENCES tb_materia(id_materia),
                                 plan_detalle_id BIGINT UNIQUE REFERENCES tb_planeamiento_detalle(id_planeamiento_detalle),
                                 id_user BIGINT REFERENCES tb_usuarios(id_user),
                                 raw_file VARCHAR(255)
);

-- Planning Capacities Table
CREATE TABLE tb_planeamiento_capacidades (
                                             id_plan_cap BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             id_planeamiento_fk BIGINT NOT NULL REFERENCES tb_planeamiento(id_planeamiento),
                                             capacidad VARCHAR(255) NOT NULL
);

-- Planning Indicators Table
CREATE TABLE tb_planeamiento_indicadores (
                                             id_plan_indicadores BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             id_planeamiento_fk BIGINT NOT NULL REFERENCES tb_planeamiento(id_planeamiento),
                                             indicador VARCHAR(255) NOT NULL
);

-- Planning Activities Table
CREATE TABLE tb_planeamiento_actividades (
                                             id_plan_act BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             id_planeamiento_fk BIGINT REFERENCES tb_planeamiento(id_planeamiento),
                                             actividad VARCHAR(255),
                                             actividad_pertenece_tipo VARCHAR(255) CHECK (actividad_pertenece_tipo IN ('ALUMNO', 'DOCENTE', 'NINGUNO')),
                                             actividad_realiza_tipo VARCHAR(255) CHECK (actividad_realiza_tipo IN ('CIERRE', 'APERTURA', 'DESARROLLO', 'SIMPLE')),
                                             desarrollo_directo VARCHAR(255)
);

-- Planning Comments Table
CREATE TABLE tb_planeamiento_comentario (
                                            id_planeamiento_comentario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            id_planeamiento_fk BIGINT NOT NULL REFERENCES tb_planeamiento(id_planeamiento),
                                            id_user BIGINT NOT NULL REFERENCES tb_usuarios(id_user),
                                            comentario VARCHAR(255) NOT NULL,
                                            root_comment_id BIGINT
);
-- Audit Table
CREATE TABLE tb_auditoria (
                              auditoria_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              user_id INTEGER,
                              operacion TEXT,
                              nombre_tabla TEXT,
                              fila_tabla BIGINT,
                              nuevos_datos JSON,
                              viejos_datos JSON,
                              timestamp TIMESTAMP,
                              ip_address TEXT,
                              user_agent TEXT
);